services:
    server:
        build: ./server
        ports: 
            - 5050:5000
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
    client:
        build: ./client
        ports:
            - 8080:3000
        volumes: 
            - ./client/src/:/app/src/
        environment:
            - WDS_SOCKET_HOST=127.0.0.1 
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db